import { program } from 'commander';
import { createReadStream, readFileSync } from 'fs';
import { google } from 'googleapis';
import { resolve } from 'node:path';

const WORKSPACE_ROOT = process.cwd();

if (
	!process.env.YOUTUBE_CLIENT_ID ||
	!process.env.YOUTUBE_CLIENT_SECRET ||
	!process.env.YOUTUBE_REFRESH_TOKEN
) {
	throw new Error('Missing YouTube API credentials in environment variables');
}

const oauth2Client = new google.auth.OAuth2({
	client_id: process.env.YOUTUBE_CLIENT_ID,
	client_secret: process.env.YOUTUBE_CLIENT_SECRET
});

oauth2Client.setCredentials({
	refresh_token: process.env.YOUTUBE_REFRESH_TOKEN
});

const youtube = google.youtube({
	version: 'v3',
	auth: oauth2Client
});

async function uploadPrompt() {
	try {
		const props = readFileSync(resolve(WORKSPACE_ROOT, 'out/prompt.manifest.json'), 'utf-8');
		const { question, answer } = JSON.parse(props);

		if (!question || !answer) {
			throw new Error('Missing question or answer in prompt manifest');
		}

		console.log('Uploading video to YouTube:', question);
		const res = await youtube.videos.insert({
			part: ['snippet', 'status'],
			requestBody: {
				snippet: {
					title: `${question} | The Earth App`,
					description: `${answer}\n\n#shorts #theearthapp #ai #cloud #intelligence #question #prompt #insights #curiosity #psychology #mentalhealth\n\nGenerated by The Earth App.`,
					tags: [
						'The Earth App',
						'AI',
						'Cloud',
						'Shorts',
						'Intelligence',
						'Insights',
						'Psychology',
						'Curiosity'
					],
					categoryId: '28' // Science & Technology
				},
				status: {
					privacyStatus: 'public',
					selfDeclaredMadeForKids: false
				}
			},
			media: {
				body: createReadStream(resolve(WORKSPACE_ROOT, 'out/prompt.mp4'))
			}
		});

		console.log('Video uploaded successfully:', res.data.id);
	} catch (error) {
		console.error('Error uploading video:', error);
		process.exit(1);
	}
}

// entrypoint

program.option('-t, --type <type>', 'Type of video to upload (prompt)');

program.parse();
const options = program.opts<{ type: string }>();

switch (options.type) {
	case 'prompt':
		await uploadPrompt();
		break;
	default:
		console.error('Invalid video type specified');
		process.exit(1);
}
