import { program } from 'commander';
import { createReadStream, readFileSync } from 'fs';
import { google } from 'googleapis';
import { resolve } from 'node:path';
import { generateYoutubeMetadataDraft } from './ai';
import {
	buildDynamicTags,
	buildFallbackHashtags,
	buildFallbackTitle,
	buildTranscriptBlock,
	chooseCategoryIdFromText,
	dedupeTags,
	normalizeWhitespace,
	toHashtag,
	trimToLength
} from './util';

const WORKSPACE_ROOT = process.cwd();

if (
	!process.env.YOUTUBE_CLIENT_ID ||
	!process.env.YOUTUBE_CLIENT_SECRET ||
	!process.env.YOUTUBE_REFRESH_TOKEN
) {
	throw new Error('Missing YouTube API credentials in environment variables');
}

const oauth2Client = new google.auth.OAuth2({
	client_id: process.env.YOUTUBE_CLIENT_ID,
	client_secret: process.env.YOUTUBE_CLIENT_SECRET
});

oauth2Client.setCredentials({
	refresh_token: process.env.YOUTUBE_REFRESH_TOKEN
});

const youtube = google.youtube({
	version: 'v3',
	auth: oauth2Client
});

type PromptManifest = {
	question: string;
	answer: string;
};

type GeneratedMetadata = {
	title: string;
	description: string;
	tags: string[];
	categoryId: string;
	hashtags?: string[];
};

const MAX_TITLE_LENGTH = 100;
const MAX_DESCRIPTION_LENGTH = 5000;
const MAX_HASHTAG_COUNT = 15;

const BRAND_TAGS = ['The Earth App', 'Earth App', 'AI', 'Cloud', 'Shorts', 'Curiosity'];

function pickBestTitle(
	aiTitle: string | undefined,
	fallbackTitle: string,
	question: string
): string {
	const normalizedAiTitle = typeof aiTitle === 'string' ? normalizeWhitespace(aiTitle) : '';
	if (normalizedAiTitle.length >= 8 && normalizedAiTitle.length <= MAX_TITLE_LENGTH) {
		const lowerAi = normalizedAiTitle.toLowerCase();
		const lowerFallback = fallbackTitle.toLowerCase();
		const lowerQuestion = normalizeWhitespace(question).toLowerCase();
		const normalizedAiBase = lowerAi.replace(/[^a-z0-9\s]/g, '');
		const normalizedFallbackBase = lowerFallback.replace(/[^a-z0-9\s]/g, '');
		const normalizedQuestionBase = lowerQuestion.replace(/[^a-z0-9\s]/g, '');
		const isNearFallback = normalizedAiBase === normalizedFallbackBase;
		const isNearQuestion = normalizedAiBase === normalizedQuestionBase;
		if (lowerAi !== lowerFallback && !isNearFallback && !isNearQuestion) {
			return trimToLength(normalizedAiTitle, MAX_TITLE_LENGTH);
		}
	}

	return fallbackTitle;
}

function buildFallbackMetadata(question: string, answer: string): GeneratedMetadata {
	const normalizedQuestion = normalizeWhitespace(question).replace(/[?!.]+$/g, '');
	const dynamicTags = buildDynamicTags(question, answer);
	const mergedTags = dedupeTags([...BRAND_TAGS, ...dynamicTags]);
	const hashtags = buildFallbackHashtags(question, answer, mergedTags);

	const title = buildFallbackTitle(question);

	const transcriptBlock = buildTranscriptBlock(question, answer);
	const answerSnippet = trimToLength(normalizeWhitespace(answer), 2400);
	const description = trimToLength(
		normalizeWhitespace(
			[
				transcriptBlock,
				answerSnippet,
				`Question explored: ${normalizedQuestion}?`,
				'Comment your take and subscribe for daily mind-expanding prompts.',
				'If this shifted how you think, share it with someone who needs the perspective.',
				hashtags.join(' '),
				'Generated by The Earth App.'
			]
				.filter(Boolean)
				.join('\n\n')
		),
		MAX_DESCRIPTION_LENGTH
	);

	return {
		title,
		description,
		tags: mergedTags,
		categoryId: chooseCategoryIdFromText(`${question} ${answer}`),
		hashtags
	};
}

async function buildOptimizedMetadata(
	question: string,
	answer: string
): Promise<GeneratedMetadata> {
	const fallback = buildFallbackMetadata(question, answer);

	try {
		const ai = await generateYoutubeMetadataDraft(question, answer);
		const mergedTags = dedupeTags([
			...(ai.tags ?? []),
			...buildDynamicTags(question, answer),
			...BRAND_TAGS
		]);

		const hashtagsFromAi = (ai.hashtags ?? [])
			.map((tag) => (tag.startsWith('#') ? tag : toHashtag(tag)))
			.filter(Boolean);
		const hashtags = dedupeTags(
			[
				...hashtagsFromAi,
				...(fallback.hashtags ?? []),
				...mergedTags.slice(0, 8).map((tag) => toHashtag(tag))
			].filter(Boolean)
		).slice(0, MAX_HASHTAG_COUNT);

		const normalizedQuestion = normalizeWhitespace(question).replace(/[?!.]+$/g, '');
		const questionLine = `Question explored: ${normalizedQuestion}?`;

		const transcriptBlock = buildTranscriptBlock(question, answer);
		const descriptionCore = ai.description
			? trimToLength(normalizeWhitespace(ai.description), 3200)
			: trimToLength(normalizeWhitespace(answer), 2400);

		const description = trimToLength(
			[
				transcriptBlock,
				descriptionCore,
				questionLine,
				'Comment your take and subscribe for daily mind-expanding prompts.',
				'If this shifted how you think, share it with someone who needs the perspective.',
				hashtags.join(' '),
				'Generated by The Earth App.'
			]
				.filter(Boolean)
				.join('\n\n'),
			MAX_DESCRIPTION_LENGTH
		);

		return {
			title: pickBestTitle(ai.title, fallback.title, question),
			description,
			tags: mergedTags.length > 0 ? mergedTags : fallback.tags,
			categoryId: ai.categoryId ?? chooseCategoryIdFromText(`${question} ${answer} ${description}`),
			hashtags
		};
	} catch (error) {
		console.warn('AI metadata generation failed, using fallback metadata.', error);
		return fallback;
	}
}

async function uploadPrompt() {
	try {
		const props = readFileSync(resolve(WORKSPACE_ROOT, 'out/prompt.manifest.json'), 'utf-8');
		const { question, answer } = JSON.parse(props) as PromptManifest;

		if (!question || !answer) {
			throw new Error('Missing question or answer in prompt manifest');
		}

		console.log('Uploading video to YouTube:', question);

		const metadata = await buildOptimizedMetadata(question, answer);

		console.log('Optimized title:', metadata.title);
		console.log('Category:', metadata.categoryId);
		const res = await youtube.videos.insert({
			part: ['snippet', 'status'],
			requestBody: {
				snippet: {
					title: metadata.title,
					description: metadata.description,
					tags: metadata.tags,
					categoryId: metadata.categoryId
				},
				status: {
					privacyStatus: 'public',
					selfDeclaredMadeForKids: false
				}
			},
			media: {
				body: createReadStream(resolve(WORKSPACE_ROOT, 'out/prompt.mp4'))
			}
		});

		console.log('Video uploaded successfully:', res.data.id);
	} catch (error) {
		console.error('Error uploading video:', error);
		process.exit(1);
	}
}

// entrypoint

program.option('-t, --type <type>', 'Type of video to upload (prompt)');

program.parse();
const options = program.opts<{ type: string }>();

switch (options.type) {
	case 'prompt':
		await uploadPrompt();
		break;
	default:
		console.error('Invalid video type specified');
		process.exit(1);
}
