name: Cron Job
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  prompt:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install Husky
        run: bun add -g husky
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Create .env File
        run: |
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}" >> .env
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }}" >> .env
          echo "YOUTUBE_CLIENT_ID=${{ secrets.YOUTUBE_CLIENT_ID }}" >> .env
          echo "YOUTUBE_CLIENT_SECRET=${{ secrets.YOUTUBE_CLIENT_SECRET }}" >> .env
          echo "YOUTUBE_REFRESH_TOKEN=${{ secrets.YOUTUBE_REFRESH_TOKEN }}" >> .env
      - name: Run Prompt Generation
        run: bun run video:prompt
      - name: Run Prompt Upload
        run: bun run upload:prompt
